version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./deploy/dockerfile/dockerfile.api
    image: fastapi_tempplate_app
    container_name: fastapi_tempplate_app
    depends_on:
      - postgres
    ports:
      - '8000:80'

  postgres:
    image: postgres:14.7
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: local_dev
      POSTGRES_USER: local_dev
      POSTGRES_DB: local_dev

  redis:
    image: redis:latest
    ports:
      - "6379:6379"