FROM --platform=linux/amd64 python:3.11-slim-bullseye as base

FROM base as builder
WORKDIR /tmp
RUN pip install poetry
COPY ./pyproject.toml ./poetry.lock* /tmp/
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes


FROM base
WORKDIR /app
COPY --from=builder /tmp/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY ./fastapi_template /app


CMD ["uvicorn", "fastapi_template.main:app", "--host", "0.0.0.0", "--port", "80"]
